version: '3.8'

services:

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    restart: unless-stopped
    volumes:
      - changedetection-data:/datastore
    environment:
      # Set base URL so notifications include correct host, and TZ for scheduling if used:
      - BASE_URL=https://detect.ranked.hu
      - TZ=Europe/Bratislava
      # You can uncomment or add other environment variables as needed, e.g. LOGGER_LEVEL, PROXY settings, etc.
    # If you have additional services for JS rendering (Playwright/Selenium), add depends_on here.
    labels:
      - "traefik.enable=true"
      # Route host detect.ranked.hu to this service
      - "traefik.http.routers.changedetection.rule=Host(`detect.ranked.hu`)"
      - "traefik.http.routers.changedetection.entrypoints=websecure"
      - "traefik.http.routers.changedetection.tls.certresolver=myresolver"
      # If you want HTTP → HTTPS redirection, you can add a web router:
      - "traefik.http.routers.changedetection-http.rule=Host(`detect.ranked.hu`)"
      - "traefik.http.routers.changedetection-http.entrypoints=web"
      - "traefik.http.routers.changedetection-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Point Traefik to the internal port 5000 of changedetection
      - "traefik.http.services.changedetection.loadbalancer.server.port=5000"
    networks:
      - coolify

# If you have other services (e.g., Playwright browser), attach them similarly to the coolify network.

volumes:
  changedetection-data:

networks:
  coolify:
    external: true
